# Generated by Django 3.2.4 on 2021-10-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_Stackoverflow',
            new_name='social_stackoverflow',
        ),
    ]
