# Generated by Django 3.2.4 on 2021-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211002_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
